language: go

go:
  - 1.6.x
  - 1.7.x
  - master

install:
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script: 
  - go test -covermode=count -coverprofile=coverage.out